version: '3'
services:
  api_data:
    build: test_api/
    ports:
      - "8000:80"
    networks:
      - main_reseau

  test_api:
    build: api_data/
    ports:
      - "8001:80"
    networks:
      - main_reseau

networks:
  main_reseau:
    driver: bridge

